name: infowindow
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  location: ^3.0.2
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^0.1.3
  sliding_up_panel:
  font_awesome_flutter:
  intl:
  rxdart:
  dio:
  shared_preferences:
  provider:
  flutter_spinkit:
  cached_network_image:
  app_settings:
  firebase_analytics:
  cloud_firestore: ^0.13.4+2
  connectivity:
  flare_flutter:
  line_icons:
  toast:
  google_fonts:
  firebase_auth: ^0.15.5+3
  google_sign_in: ^3.2.4
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/flr/